// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.696
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func AddExercises() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><h2 class=\"text-2xl font-bold text-center mb-8\">Add Exercises</h2><div class=\"mb-4\"><label for=\"workout\" class=\"block text-gray-700\">Select Workout:</label> <select id=\"workout\" name=\"workout\" class=\"form-select mt-1 block w-full\" required><!-- Example options, these should be dynamically populated --><option value=\"Workout 1\">Workout 1</option> <option value=\"Workout 2\">Workout 2</option><!-- More options --></select></div><form action=\"/add-exercise\" method=\"post\" id=\"exercise-form\" class=\"mb-8\"><div class=\"mb-4\"><label for=\"exercise\" class=\"block text-gray-700\">Exercise Name:</label> <input type=\"text\" id=\"exercise\" name=\"exercise\" class=\"form-input mt-1 block w-full\" required></div><div class=\"mb-4\"><label for=\"sets\" class=\"block text-gray-700\">Sets:</label> <input type=\"number\" id=\"sets\" name=\"sets\" class=\"form-input mt-1 block w-full\" required></div><div class=\"mb-4\"><label for=\"reps\" class=\"block text-gray-700\">Reps:</label> <input type=\"number\" id=\"reps\" name=\"reps\" class=\"form-input mt-1 block w-full\" required></div><button type=\"submit\" class=\"bg-blue-700 hover:bg-blue-900 text-white font-bold py-2 px-4 rounded\">Add Exercise</button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
